### ISSUE TITLE
Unable to persist new item that is dropped on a Map canvas

### ISSUE THREAD

**Issue by markhm** [LeadingEdgeForum/atlas2#289]
Hi team,

I downloaded Atlas2, which I am trying to get working on macOS. All seems to work fine, until the moment that I drop an item (e.g. a User) on the canvas of a new Map and I want to commit (Create) the popup screen where I've filled the Name and Description. In the logs I see the following post to the server:

`  web_1    | 172.19.0.1 - - [07/May/2018:18:17:54 +0000] "POST /api/workspace/5aec6c789ae57a0011bedadc/map/5aec6caf9ae57a0011bedae2/user/ HTTP/1.1" 404 213 "http://localhost:6001/map/5aec6caf9ae57a0011bedae2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36"`

but in some way this 'Create' is never committed, so the popup is never removed again.

I've tried under various browsers (Chrome, Safari, Opera, Firefox), and from a VMWare Windows instance with Edge, all with the same result, so I suspect it is a server-side problem. 

Strange thing is that parts of the application state (tied to the username I created) áre maintained between sessions, since I've been able to login and see the organisation I created after I restarted the server ('docker-compose up'). 

Please let me know if I can help in any way with isolating the problem.

Thanks, Mark

**Comment by cdaniel** [comment]
Try out the v2-service-branch branch.

Master contains some unfinished work in progress (and rather heavy change in approach to how maps are stored).
